name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      working-directory: ./3_Implementation
      run: ./configure
      
    - name: Install dependencies
      working-directory: ./3_Implementation
      run: make
      
    - name: Run check
      working-directory: ./3_Implementation
      run: make check
      
    - name: Run distcheck
      working-directory: ./3_Implementation
      run: make distcheck
